### ISSUE TITLE
Movie sets: List of items on top of description

### ISSUE THREAD

**Issue by eugeneromero** [jester-xbmc/skin.amber#95]
Hi!

I am seeing a visual bug when scrolling through the Movies view in Kodi/Amber. When selecting a Movie Set, the Description and List of Items of the set are displayed on top of each other, making both unreadable.

I was not able to find a setting to turn either one off. This happens with any view having a "Plot/Description" box.

Thank you very much for looking into this and making this great skin!

Amber version: 3.0.8
Kodi version: OpenELEC 8.0.4

**Comment by jester-xbmc** [comment]
Hi, could you attached a screenshot of what you are seeing, as i'm not using movie sets.
Thanks

**Comment by eugeneromero** [comment]
Absolutely! Here you go:

![20180619_065809](https://user-images.githubusercontent.com/1104426/41602865-5b592856-73a1-11e8-8de9-b69992528a05.jpg)
![20180619_065816](https://user-images.githubusercontent.com/1104426/41602867-5b75a18e-73a1-11e8-905c-a9604d27ca17.jpg)

As you can see, the list of movies in the set and the description of the set itself are superimposed. Let me know if any other info is needed.

Thanks!

**Comment by KBGrammer** [comment]
I have found a way to resolve this, but the secondary effect of my fix is that other views don't work right.

Basically, it only takes a few lines to prevent any plot summary from showing up at all, but it turns out that one of the other views uses the plot summary with no list of members and my fix breaks that.

I'll look into resolving that and hopefully come up with a clean solution to both cases.

**Comment by jester-xbmc** [comment]
fix in https://github.com/jester-xbmc/skin.amber/commit/a3078a081a2903e53693c5a054da25c03b6b408c
